[package]
name = "waveshare-sx1262-hat-rust"
version = "0.1.0"
edition = "2021"
rust-version = "1.75"
description = "UART driver for the Waveshare SX1262 868M LoRa HAT on Raspberry Pi"
license = "Apache-2.0"
repository = "ttps://github.com/nondetalle/waveshare-sx1262-hat-rust.git"
keywords = ["lora", "sx1262", "raspberry-pi", "uart", "radio"]
categories = ["embedded", "hardware-support"]

[dependencies]
thiserror = "2"
parking_lot = "0.12"
rppal = "0.20"
serialport = { version = "4.6", default-features = false}

[features]
trace = []
